[WFGP-232] Add phase attribute to line-ending filter
wildfly/galleon-plugins pull request #235
Opened 2022-08-23 10:04 UTC by spyrkob

Issue: https://issues.redhat.com/browse/WFGP-232

This would allow to run the line-ending filter after FINALIZING phase tasks like this:

```
<tasks xmlns="urn:wildfly:wildfly-feature-pack-tasks:3.1">
    <delete path="docs/licenses/licenses.html"/>
    <xml-merge basedir="docs/licenses" output="docs/licenses/licenses.xml">
        <filter pattern="*-licenses.xml" include="true"/>
    </xml-merge>
    <transform stylesheet="docs/licenses/licenses.xsl" src="docs/licenses/licenses.xml" output="docs/licenses/licenses.html" phase="FINALIZING"/>
    <line-endings phase="FINALIZING">
      <windows>
        <filter pattern="docs/licenses/licenses.html" include="true"/>
      </windows>
    </line-endings>
</tasks>
```

2022-08-24 15:29 UTC, spyrkob commented
Wildfly changes to force the linux line endings in licenses: https://github.com/spyrkob/wildfly/commit/12f0d5bcff9bf2fd5b9893e33677b797dae569a9

2022-08-29 09:24 UTC, jfdenise requested changes

2022-08-29 09:24 UTC, jfdenise commented on galleon-plugins/src/main/java/org/wildfly/galleon/plugin/config/WildFlyPackageTasksParser20.java
> +                            CollectionUtils.add(filters, filter);
Should be filters = CollectionUtils.add(filters, filter); otherwise the filters are lost.

2022-08-29 09:24 UTC, jfdenise commented on galleon-plugins/src/main/java/org/wildfly/galleon/plugin/config/WildFlyPackageTasksParser31.java
> +            final WildFlyPackageTasksParser20.Attribute attribute = WildFlyPackageTasksParser20.Attribute.of(reader.getAttributeName(i));
Should be Attribute attribute, here we are using WildFlyPackageTasksParser20

2022-08-29 09:26 UTC, jfdenise commented
In the task example you provided, using windows platform seems not correct, we would want to generate line endings for unix even on windows. So should be unix, right?

2022-08-29 09:28 UTC, jfdenise commented on galleon-plugins/src/main/java/org/wildfly/galleon/plugin/config/LineEndingsTask.java
> +/**
The license header is not aligned with other files.

2022-08-30 07:35 UTC, spyrkob commented
Thanks @jfdenise, I pushed the fixes

2022-08-30 08:42 UTC, jfdenise approved these changes

2022-08-30 08:43 UTC, merged